/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Reports;

import TheBusiness.Business.Business;
import javax.swing.JPanel;

/**
 *
 * @author csong
 */

public class ReportViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportViewJPanel
     */
    Business business;
    JPanel csp;
    public ReportViewJPanel(Business business, JPanel csp) {
        initComponents();
        this.business = business;
        this.csp = csp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostValuableCustomer = new javax.swing.JButton();
        btnSupplierReport = new javax.swing.JButton();
        btnMostExpensiveProduct = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        btnMostValuableCustomer.setBackground(new java.awt.Color(102, 153, 255));
        btnMostValuableCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnMostValuableCustomer.setText("Most Valuable Customers");
        btnMostValuableCustomer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostValuableCustomer.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMostValuableCustomer.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMostValuableCustomer.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMostValuableCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostValuableCustomerIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnSupplierReport.setBackground(new java.awt.Color(102, 153, 255));
        btnSupplierReport.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplierReport.setText("Supplier Report");
        btnSupplierReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSupplierReport.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSupplierReport.setMinimumSize(new java.awt.Dimension(20, 23));
        btnSupplierReport.setPreferredSize(new java.awt.Dimension(240, 30));
        btnSupplierReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierReportIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnMostExpensiveProduct.setBackground(new java.awt.Color(102, 153, 255));
        btnMostExpensiveProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnMostExpensiveProduct.setText("Most Expensive Products Report");
        btnMostExpensiveProduct.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostExpensiveProduct.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMostExpensiveProduct.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMostExpensiveProduct.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMostExpensiveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostExpensiveProductIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Performance Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostExpensiveProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(btnMostValuableCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupplierReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblTitle)
                .addGap(57, 57, 57)
                .addComponent(btnMostExpensiveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnMostValuableCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnSupplierReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostValuableCustomerIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostValuableCustomerIdentifyResourceAssetsActionPerformed

        // TODO add your handling code here:
        CustomersReportJPanel crjp = new CustomersReportJPanel(business, csp);

        csp.add("View", crjp);
        ((java.awt.CardLayout) csp.getLayout()).next(csp);
    }//GEN-LAST:event_btnMostValuableCustomerIdentifyResourceAssetsActionPerformed

    private void btnSupplierReportIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierReportIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupplierReportIdentifyResourceAssetsActionPerformed

    private void btnMostExpensiveProductIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostExpensiveProductIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        ProductReportJPanel prjp = new ProductReportJPanel(business, csp);

        csp.add("ViewMostExpensiveProducts", prjp);
        ((java.awt.CardLayout) csp.getLayout()).next(csp);
    }//GEN-LAST:event_btnMostExpensiveProductIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostExpensiveProduct;
    private javax.swing.JButton btnMostValuableCustomer;
    private javax.swing.JButton btnSupplierReport;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
